### ISSUE TITLE
Test the website

### ISSUE THREAD

**Issue by canedobox** [canedobox/gymproject#17]
Test the website and its functionalities on multiple browsers: Google Chrome, Firefox and Microsoft Edge.

**Comment by canedobox** [comment]
The website and its functionalities have been tested on multiple browsers: Google Chrome, Firefox and Microsoft Edge.

**Website test 1. Load pages**
When loading the pages hosted on GitHub Pages from Google Chrome or Microsoft Edge, a warning is displayed on the console: “Error with Permissions-Policy header: Origin trial controlled feature not enabled: 'interest-cohort'.”

This warning message should be ignored and won't be worked on. The warning is related to GitHub Pages disabling FLoC as default for all the sites served from github.io, learn more:

•	https://docs.gitlab.com/ee/user/admin_area/settings/floc.html
•	https://github.blog/changelog/2021-04-27-github-pages-permissions-policy-interest-cohort-header-added-to-all-pages-sites/

**Home page loaded with no errors**
<img width="452" alt="image" src="https://user-images.githubusercontent.com/65631733/207175748-a1d51977-4ce1-4488-ad57-bff4bed78db6.png">

**Classes page loaded with no errors**
<img width="452" alt="image" src="https://user-images.githubusercontent.com/65631733/207175884-2c02cf3d-2563-4622-96ad-a2cc157b476e.png">

**Timetable page loaded with no errors**
<img width="452" alt="image" src="https://user-images.githubusercontent.com/65631733/207175971-d4e74df1-8e80-456e-b953-0c5d135aa258.png">

**Contact page loaded with no errors**
<img width="452" alt="image" src="https://user-images.githubusercontent.com/65631733/207176164-dfa90410-118a-49bc-b508-c3988bc6a449.png">

**Comment by canedobox** [comment]
**Website test 2. Links**
1.	All the navigation menu links and page links have been tested and are redirecting the user to the right pages.
2.	The footer navigation links display an alert when clicked as the policies are not part of the project scope.

<img width="452" alt="image" src="https://user-images.githubusercontent.com/65631733/207176711-52fc0826-d91a-4fb4-9380-aace1954d4a2.png">

**Comment by Myhome210190** [comment]
**Website test 3. Contact form**
Contact form validation have been tested and it is displaying validation messages correctly. 

In order to pass the form validation, the user must: 

1. Enter a name with at least 2 characters. 
2. Enter a valid email address. 
3. Select a subject. 
4. Provide a message with a maximum of 500 characters. 

If a form field fails validation, a message should be display to the user and a console message should be logged: 
![image](https://user-images.githubusercontent.com/119354318/207178798-7b2eed87-7ac6-458f-b918-3c03ca034d67.png)

When all the form fields pass the validations, a confirmation message should be displayed to the user and a console message should be logged: 
![image](https://user-images.githubusercontent.com/119354318/207179190-7537c12d-c48b-41e8-89d3-5de56e369980.png)
